"use client"
import "./globals.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faHome,
  faEnvelope,
  faUsers,
  faRocket,
  faWrench,
} from "@fortawesome/free-solid-svg-icons";
import Link from "next/link";
import { usePathname } from "next/navigation"; // Import usePathname

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen bg-gray-100 flex flex-col">
          <div className="flex flex-grow h-full">
            {/* Sidebar with Icons */}
            <div className="bg-white w-16 pt-24 p-4 flex flex-col items-center space-y-6 rounded-lg mt-2 mb-2 ml-3 shadow-lg">
              <SidebarLink href="/" icon={faHome} />
              <SidebarLink href="/inbox" icon={faEnvelope} />
              <SidebarLink href="/customers" icon={faUsers} />
              <SidebarLink href="/pipeline" icon={faRocket} />
              <SidebarLink href="/settings" icon={faWrench} />
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}

function SidebarLink({ href, icon }) {
  const pathname = usePathname(); // Get the current route

  const isActive = pathname === href; // Check if this link is the active page

  return (
    <Link href={href}>
      <div
        tabIndex={0}
        className={`flex items-center justify-center w-9 h-9 p-2 rounded-md cursor-pointer transition duration-300 ${
          isActive
            ? "bg-pink-500 text-white"
            : "bg-gray-300 text-black hover:bg-pink-500 hover:text-white"
        }`}
      >
        <FontAwesomeIcon icon={icon} size="lg" />
      </div>
    </Link>
  );
}
